# Numpy array vs Python lists

In [3]:
# speed - speed of numpy is faster than list 
# list 
a = [i for i in range(10000000)]
b = [i for i in range (10000000 , 20000000)]

c = []
# Import time to check how much time is required to perform operation in a list 
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

1.0703768730163574


In [5]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()

c = a + b
print(time.time() - start)

0.04221057891845703


In [6]:
# memory - As such the diffrence between memory required by a list or array of int64 is not much but if we make a array of int16 or int32 or int8 it will occupy less space 

a = [i for i in range(10000000)]

import sys
sys.getsizeof(a)

89095160

In [9]:
a = np.arange(10000000 , dtype= np.int16)
sys.getsizeof(a)

20000112

In [10]:
# convinence - working with numpy is easy as comparision to list 

# Advanced Indexing

In [18]:
# Normal indexing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a[1:,1]

array([ 5,  9, 13, 17, 21])

In [30]:
# Fancy Indexing - when finding pattern of indexing is not possible than fancy indexing is used 
print('-------------------for example we want row 1 , 3 , 4 and 6--------------------')
print(a[[0,2,3,5]])
print('-------------------for example we want column 1 , 3 , 4 ------------------------')
print(a[:,[0,2,3]])

-------------------for example we want row 1 , 3 , 4 and 6--------------------
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]
-------------------for example we want column 1 , 3 , 4 ------------------------
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [41]:
# Boolean Indexing - It is used when logic is required 

# create a random array of range 1 to 100 and 24 elements are selected
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[68, 17, 54, 88],
       [97, 46, 14, 10],
       [10, 69, 96, 29],
       [58, 12, 35, 16],
       [83, 68, 66,  6],
       [90, 12,  4, 91]], dtype=int32)

In [42]:
# Find all numbers greater than 50
a[a > 50]

array([68, 54, 88, 97, 69, 96, 58, 83, 68, 66, 90, 91], dtype=int32)

In [43]:
# Find all numbers greater than 50 and even
a[(a > 50) & (a % 2 == 0)]

array([68, 54, 88, 96, 58, 68, 66, 90], dtype=int32)

# BroadCasting 
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic opertaions.THe smaller array is "broadcast" across the larger array so that they have compatible shapes

In [51]:
# Same Shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print('-----------------------Array A----------------------')

print(a)
print('-----------------------Array B----------------------')
print(b)
print('-----------------------Sum----------------------')
print(a+b)

-----------------------Array A----------------------
[[0 1 2]
 [3 4 5]]
-----------------------Array B----------------------
[[ 6  7  8]
 [ 9 10 11]]
-----------------------Sum----------------------
[[ 6  8 10]
 [12 14 16]]


In [57]:
# Different Shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print('-----------------------Array A----------------------')

print(a)
print('-----------------------Array B----------------------')
print(b)
print('-----------------------Sum----------------------')
print(a+b)

-----------------------Array A----------------------
[[0 1 2]
 [3 4 5]]
-----------------------Array B----------------------
[[0 1 2]]
-----------------------Sum----------------------
[[0 2 4]
 [3 5 7]]


## BroadCasting Rules
### 1. Make the two arrays have the same number of dimensions.
            if a numbers of dimensions of the two arrays are diffrent, add new dimensions with size 1 to the head of the array with the smaller dimension.
### 2. Make each dimension of the two arrays the same size 
        if the size of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
        if there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.