# Numpy array vs Python lists

In [2]:
# speed - speed of numpy is faster than list 
# list 
a = [i for i in range(10000000)]
b = [i for i in range (10000000 , 20000000)]

c = []
# Import time to check how much time is required to perform operation in a list 
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

3.6520535945892334


In [3]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()

c = a + b
print(time.time() - start)

0.2956717014312744


In [4]:
# memory - As such the diffrence between memory required by a list or array of int64 is not much but if we make a array of int16 or int32 or int8 it will occupy less space 

a = [i for i in range(10000000)]

import sys
sys.getsizeof(a)

89095160

In [5]:
a = np.arange(10000000 , dtype= np.int16)
sys.getsizeof(a)

20000112

In [6]:
# convinence - working with numpy is easy as comparision to list 

# Advanced Indexing

In [7]:
# Normal indexing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a[1:,1]

array([ 5,  9, 13, 17, 21])

In [9]:
# Fancy Indexing - when finding pattern of indexing is not possible than fancy indexing is used 
print('-------------------for example we want row 1 , 3 , 4 and 6--------------------')
print(a[[0,2,3,5]])
print('-------------------for example we want column 1 , 3 , 4 ------------------------')
print(a[:,[0,2,3]])

-------------------for example we want row 1 , 3 , 4 and 6--------------------
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]
-------------------for example we want column 1 , 3 , 4 ------------------------
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]


In [10]:
# Boolean Indexing - It is used when logic is required 

# create a random array of range 1 to 100 and 24 elements are selected
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[79, 73, 62, 68],
       [74, 60,  6, 24],
       [90, 95, 54, 25],
       [10,  4, 41, 12],
       [36, 15, 48, 42],
       [35, 29,  6, 13]], dtype=int32)

In [11]:
# Find all numbers greater than 50
a[a > 50]

array([79, 73, 62, 68, 74, 60, 90, 95, 54], dtype=int32)

In [12]:
# Find all numbers greater than 50 and even
a[(a > 50) & (a % 2 == 0)]

array([62, 68, 74, 60, 90, 54], dtype=int32)

# BroadCasting 
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic opertaions.THe smaller array is "broadcast" across the larger array so that they have compatible shapes

In [13]:
# Same Shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print('-----------------------Array A----------------------')

print(a)
print('-----------------------Array B----------------------')
print(b)
print('-----------------------Sum----------------------')
print(a+b)

-----------------------Array A----------------------
[[0 1 2]
 [3 4 5]]
-----------------------Array B----------------------
[[ 6  7  8]
 [ 9 10 11]]
-----------------------Sum----------------------
[[ 6  8 10]
 [12 14 16]]


In [14]:
# Different Shape
a = np.arange(8).reshape(2,4)
b = np.arange(2).reshape(3,1)
print('-----------------------Array A----------------------')

print(a)
print('-----------------------Array B----------------------')
print(b)
print('-----------------------Sum----------------------')
print(a+b)

ValueError: cannot reshape array of size 2 into shape (3,1)

## BroadCasting Rules
### 1. Make the two arrays have the same number of dimensions.
            if a numbers of dimensions of the two arrays are diffrent, add new dimensions with size 1 to the head of the array with the smaller dimension.
### 2. Make each dimension of the two arrays the same size 
        if the size of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
        if there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.