In [1]:
import numpy as np

# Array Functions

In [2]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[81., 21., 20.],
       [86., 29., 25.],
       [53., 75.,  1.]])

In [15]:
# max/min/sum/prod
# 0 -> col and 1 -> row
# max of all rows
print(np.max(a1 , axis = 1))
# max of all columns
print(np.max(a1 , axis = 0))
print(np.min(a1 , axis = 0))
#sum of values of a row
print(np.sum(a1 , axis = 1))
# product of all values in a array
print(np.prod(a1))

[81. 86. 75.]
[86. 75. 25.]
[53. 21.  1.]
[122. 140. 129.]
8431559325000.0


In [16]:
# mean/median/std/var
np.mean(a1 , axis= 0)

array([73.33333333, 41.66666667, 15.33333333])

In [17]:
np.median(a1)

np.float64(29.0)

In [18]:
np.std(a1)

np.float64(29.27308627813121)

In [19]:
# Trignometric Function - sin/cos/tan/cosec/sec
np.sin(a1)

array([[-0.62988799,  0.83665564,  0.91294525],
       [-0.92345845, -0.66363388, -0.13235175],
       [ 0.39592515, -0.38778164,  0.84147098]])

In [24]:
# Dot Product - number of columns of first array should be equal to the number of rows in a second array
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(20).reshape(4,5)

np.dot(a2,a3)

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [31]:
# log and exponents
print(np.log(a1))
print('_______________________________________________________________')
print(np.exp(a1))

[[4.39444915 3.04452244 2.99573227]
 [4.4543473  3.36729583 3.21887582]
 [3.97029191 4.31748811 0.        ]]
_______________________________________________________________
[[1.50609731e+35 1.31881573e+09 4.85165195e+08]
 [2.23524660e+37 3.93133430e+12 7.20048993e+10]
 [1.04137594e+23 3.73324200e+32 2.71828183e+00]]


In [36]:
# round/floor/ceil
print(np.round(np.random.random((2,3))))
print('_______________________________________________________________')
print(np.floor(np.random.random((2,3))))
print('_______________________________________________________________')
print(np.ceil(np.random.random((2,3))))

[[0. 1. 0.]
 [0. 0. 1.]]
_______________________________________________________________
[[0. 0. 0.]
 [0. 0. 0.]]
_______________________________________________________________
[[1. 1. 1.]
 [1. 1. 1.]]


# Indexing Slicing

In [37]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [39]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1[0] 
# positive indexing is from left to right

np.int64(0)

In [41]:
a1[-4]
# Negative indexing is from right to left

np.int64(6)

In [42]:
a2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
print(a2[0][3] )
# or 
print(a2[1,2])

3
6


In [48]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [54]:
# to access data from 3D array check the element is in first part or second then check its row and then column
print(a3[1 , 0 , 1])

5


In [58]:
# slicing - first value shows the index of the starting part , second value shows the ending index and third shows the space 
print(a1[2:5])
print(a1[2:5:2])

[2 3 4]
[2 4]


In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
# taking 0th row and all columns of that row
print(a2[0 ,:])
print('---------------------------------')
# taking all rows of 1 column
print(a2[: ,1] )
print('---------------------------------')
# taking element of 0th row first column
print(a2[0 ,1] )

[0 1 2 3]
---------------------------------
[1 5 9]
---------------------------------
1


In [65]:
# taking all rows from 1 and column 1 to 2
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [66]:
# Taking extreme values - first colon of rows and columns show need of all rows and columns but the second colon shows the gap of 2 rows and 3 columns
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [70]:

a2[0::1, 1::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [81]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
# it is used to access array from 3d to 2d 
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
# taking second row of first array
a3[0,1]

array([3, 4, 5])

In [88]:
a3[2 , 1: , 1:]

array([[22, 23],
       [25, 26]])

In [89]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating


In [94]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [100]:
a2
for i in np.nditer(a2):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11


In [101]:
a3
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [102]:
# Transpose - Making rows as columns and columns as rows 
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [103]:
# ravel - convert nd array into 1d array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [111]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
# Horizontal stacking - adding array after array (In Stacking all arrays must have same rows and columns)
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [113]:
# vertical Stacking - adding array one below another 
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [115]:
# Horizontal Splitting - columns must be divisible by the number of splits you want
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [123]:
# Vertical Splitting - rows must be divisible by the number of splits you want
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]