In [1]:
# Numpy is a One Dimensional array to store homogeneous data and solve mathematical problems 
import numpy as np
arr = np.array([1,2,3])
# To print the Array
print(arr)
# To check the type of variable 
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# From numpy we can also make 2D or 3D arrays 
brr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print (brr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# we can also create array of different data types with "dtype" parameter
crr = np.array([1,2,0],dtype= float)
print(crr)

[1. 2. 0.]


In [4]:
# np.arange is a function which is used for make a array in a range 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# np.arange function is also used if want to skip numbers in a range 
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
# with reshape function we can make a multidimensional array 
np.arange(1,11).reshape(2,5)
# here 5 * 2 = 10 which is equal to the number of elments in the range

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
   # np.ones and np.zeros
np.ones((3,4))
# make an array where all values are initiated with 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((2,3))
# make an array where all values are initiated with 0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# np.random - To initiate all values with random values 
np.random.random((3,4))

array([[0.69418378, 0.6977412 , 0.75481764, 0.97051601],
       [0.92031314, 0.55214682, 0.11903317, 0.00468973],
       [0.65068178, 0.98291778, 0.37837101, 0.0850506 ]])

In [10]:
# np.linspace - used to generate values between the range of first two elements and thrird value shows the number of elements with equal distance  
np.linspace(-10 , 10 , 2)

array([-10.,  10.])

In [11]:
# np.identity - to create identity matrix
# in numpy default value is float to typecast it into integer we use dtype
np.identity(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
a1 = np.arange(11)
a2 = np.arange(12 , dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Array Attributes

In [13]:
# ndim - used to check the dimensions of an array
a2.ndim

2

In [16]:
# Shape -    
a2.shape

(3, 4)

In [88]:
# size - number of items
a3.size

8

In [89]:
# itemsize - it shows the number of bits data element occupies
a3.itemsize

8

In [90]:
# dtype - it shows type of data 
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing DataTypes

In [91]:
# astype - To change the type of data from int to float or vice versa at all
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operation

In [92]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
# Scalar Operation - When an array is multiplied with a number 
# Arithmetic Operation -
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [94]:
# Relational operation
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [95]:
# Vector Operation - When operations are performed on two arrays
# arithmetic - Shapes must be same of all arrays 
a1 + a2
a1 < a2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])