In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
a

array([97,  8, 18,  6, 33, 38, 56, 87,  6,  3, 92, 78, 30, 10, 15],
      dtype=int32)

# Sorting - 
Arrange elements in ascending order
## np.sort(a , axis = -1 , kind = None , order = None)
1. a - array 
2. axis - int or None (optional)
3. kind - quicksort , mergesort,heapsort,stable (optional)
4. order - str or list of str (optional)

In [5]:

np.sort(a)

array([ 9, 12, 12, 30, 40, 46, 51, 51, 52, 57, 61, 63, 71, 81, 89],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,25).reshape(5,5)
b

array([[20, 57, 26, 25,  2],
       [92,  1,  6,  2, 86],
       [69, 79, 83, 96, 23],
       [25, 20, 72, 10, 10],
       [79, 50, 17, 90,  1]], dtype=int32)

In [5]:
# In 2D array axis = 1 ----> Row wise sorting 
# axis = 0 -----> Column Wise Sorting
# By default Row Wise Sorting
print("--------------------Row Wise Sorting-------------------------------")
print(np.sort(b))
print("--------------------column Wise Sorting-------------------------------")
print(np.sort(b , axis=0))

--------------------Row Wise Sorting-------------------------------
[[ 2 20 25 26 57]
 [ 1  2  6 86 92]
 [23 69 79 83 96]
 [10 10 20 25 72]
 [ 1 17 50 79 90]]
--------------------column Wise Sorting-------------------------------
[[20  1  6  2  1]
 [25 20 17 10  2]
 [69 50 26 25 10]
 [79 57 72 90 23]
 [92 79 83 96 86]]


In [6]:
# Sorting in descending Order - 
np.sort(a)[::-1]

array([97, 92, 87, 78, 56, 38, 33, 30, 18, 15, 10,  8,  6,  6,  3],
      dtype=int32)

# np.append
The numpy.append() appends values along the mentioned axis at the end of the array

In [7]:
np.append(a , 100)

array([ 97,   8,  18,   6,  33,  38,  56,  87,   6,   3,  92,  78,  30,
        10,  15, 100])

In [11]:
# Add a column in 2d array
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[20., 57., 26., 25.,  2.,  1.],
       [92.,  1.,  6.,  2., 86.,  1.],
       [69., 79., 83., 96., 23.,  1.],
       [25., 20., 72., 10., 10.,  1.],
       [79., 50., 17., 90.,  1.,  1.]])

# np.concatenate
numpy.concatenate() function concatenates a sequence of arrays along an existing axis

In [40]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
with the help of np.unique() method, we can get the unique values from the array given as parameter

In [45]:
arr = np.array([1,11,1,1,7,2,3,2,3,1,3,1,3,2,3,11,2])
arr

array([ 1, 11,  1,  1,  7,  2,  3,  2,  3,  1,  3,  1,  3,  2,  3, 11,  2])

In [46]:
np.unique(arr)

array([ 1,  2,  3,  7, 11])

# np.expand_dims
with the help of Numpy.expand_dims() method, we can get the extended dimensions of an array

In [47]:
# 1d ----> 2d 
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [52]:
np.expand_dims(a,axis=1)

array([[51],
       [ 9],
       [57],
       [63],
       [61],
       [12],
       [51],
       [81],
       [30],
       [46],
       [89],
       [40],
       [71],
       [12],
       [52]], dtype=int32)

In [51]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where
returns the indices of elements in an input array where the given condition is satisfied

In [12]:
a

array([97,  8, 18,  6, 33, 38, 56, 87,  6,  3, 92, 78, 30, 10, 15],
      dtype=int32)

In [13]:
# Find all values greater than 50 
np.where(a>50)

(array([ 0,  6,  7, 10, 11]),)

In [56]:
# Replace all values > 50 with 0
# np.where(condition , true , false)
np.where(a > 50 , 0 , a)

array([ 0,  9,  0,  0,  0, 12,  0,  0, 30, 46,  0, 40,  0, 12,  0],
      dtype=int32)

In [57]:
# Replace all even values with 1 greater than it and all odd values by one less than it
np.where(a % 2 == 0 , a+1 , a-1)

array([50,  8, 56, 62, 60, 13, 50, 80, 31, 47, 88, 41, 70, 13, 53],
      dtype=int32)

# np.argmax
returns indices of the max element of the array in a particular axis


In [58]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [59]:
np.argmax(a)

np.int64(10)

In [60]:
np.argmin(a)

np.int64(1)

In [61]:
b

array([[79, 27, 33, 78,  4],
       [ 6, 40, 53, 69, 23],
       [69,  4, 39, 23, 49],
       [36, 73,  4, 43, 85],
       [74, 75, 42, 83, 28]], dtype=int32)

In [63]:
np.argmax(b , axis = 0)

array([0, 4, 1, 4, 3])

In [64]:
np.argmin(b , axis = 1)

array([4, 0, 1, 2, 4])

# np.cumsum
used when we want to compute the cumulative sum of array elements over a given axis

In [65]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [66]:
np.cumsum(a)

array([ 51,  60, 117, 180, 241, 253, 304, 385, 415, 461, 550, 590, 661,
       673, 725])

In [67]:
b

array([[79, 27, 33, 78,  4],
       [ 6, 40, 53, 69, 23],
       [69,  4, 39, 23, 49],
       [36, 73,  4, 43, 85],
       [74, 75, 42, 83, 28]], dtype=int32)

In [69]:
np.cumsum(b ,axis = 1 )

array([[ 79, 106, 139, 217, 221],
       [  6,  46,  99, 168, 191],
       [ 69,  73, 112, 135, 184],
       [ 36, 109, 113, 156, 241],
       [ 74, 149, 191, 274, 302]])

In [70]:
# np.cumprod - cumulative product
np.cumprod(a)

array([                 51,                 459,               26163,
                   1648269,           100544409,          1206532908,
               61533178308,       4984187442948,     149525623288440,
          6878178671268240,  612157901742873360, 6039571996005382784,
       4534498021062490496, -926255968378768896, 7174921865432672256])

# np.percentile 
used to compute the nth percentile of the given data

In [71]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [73]:
# maximum value of a array ----> 100 % of a array is biggest number 
np.percentile(a , 100)

np.float64(89.0)

In [74]:
# minimum value of a array 
np.percentile(a , 0)

np.float64(9.0)

In [75]:
# middle number 
np.percentile(a , 50)

np.float64(51.0)

# np.histogram
it represents the frequency of data distribution in the graphical form

In [76]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [79]:
np.histogram(a , bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 0, 1, 2, 4, 2, 1, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [80]:
# it shows in bin size 0-10 there is 1 item in 10-20 there is 2 and so on

# Corelation coefficient -
it shows how much the two values are corelated to each other


In [82]:
salary = np.array([20000,30000,40000,80000,1000000])
experience = np.array([1,2,3,4,5])

In [84]:
np.corrcoef(salary,experience)
# It shows relation of salary with salary , salalry with experience , experience with salary and experience and experience

array([[1.        , 0.74113754],
       [0.74113754, 1.        ]])

# np.isin
we can see that one array having values are checked in a different numpy array having differemt elements with different sizes

In [86]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [92]:
items = [10,20,30,40,50]
np.isin(a , items)
# It is used to check multiple values in an array if they exist it shows true else false 

array([False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False])

In [94]:
a[np.isin(a , items)]
# It shows only the elements which is present 

array([30, 40], dtype=int32)

# np.flip
It makes the mirror image of the given array

In [95]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [96]:
np.flip(a)

array([52, 12, 71, 40, 89, 46, 30, 81, 51, 12, 61, 63, 57,  9, 51],
      dtype=int32)

In [97]:
b

array([[79, 27, 33, 78,  4],
       [ 6, 40, 53, 69, 23],
       [69,  4, 39, 23, 49],
       [36, 73,  4, 43, 85],
       [74, 75, 42, 83, 28]], dtype=int32)

In [98]:
np.flip(b)
# It will flip row wise as well as column wise

array([[28, 83, 42, 75, 74],
       [85, 43,  4, 73, 36],
       [49, 23, 39,  4, 69],
       [23, 69, 53, 40,  6],
       [ 4, 78, 33, 27, 79]], dtype=int32)

In [99]:
# Row Wise flip
np.flip(b , axis = 1)

array([[ 4, 78, 33, 27, 79],
       [23, 69, 53, 40,  6],
       [49, 23, 39,  4, 69],
       [85, 43,  4, 73, 36],
       [28, 83, 42, 75, 74]], dtype=int32)

In [100]:
# column Wise flip
np.flip(b , axis = 0)

array([[74, 75, 42, 83, 28],
       [36, 73,  4, 43, 85],
       [69,  4, 39, 23, 49],
       [ 6, 40, 53, 69, 23],
       [79, 27, 33, 78,  4]], dtype=int32)

# np.put 
It will replace the array element 

In [101]:
a

array([51,  9, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [103]:
np.put(a,[0,1],[2,3]) 
# np.put(array , [indexes at which changes used to be done] , [what elements you want to put])
a
# These changes are permanent 

array([ 2,  3, 57, 63, 61, 12, 51, 81, 30, 46, 89, 40, 71, 12, 52],
      dtype=int32)

In [105]:
np.put(a , np.where(a % 2 == 0) , 0)
a

array([ 0,  3, 57, 63, 61,  0, 51, 81,  0,  0, 89,  0, 71,  0,  0],
      dtype=int32)

# np.delete
returns a new array with the deletion of sub-arrays along with the axis

In [106]:
a

array([ 0,  3, 57, 63, 61,  0, 51, 81,  0,  0, 89,  0, 71,  0,  0],
      dtype=int32)

In [109]:
np.delete(a,[0,6,8])
# Indices you wants to delete

array([ 3, 57, 63, 61,  0, 81,  0, 89,  0, 71,  0,  0], dtype=int32)

# Set Functions
1. np.union1d
2. np.insersectt1d
3. np.setdiff1d
4. np.setxor1d
5. np.isin1d

In [124]:
m = np.array([1,2,3,4,5,6,7])
n = np.array([4,5,6,7,8,9,10,11])

np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
np.intersect1d(m,n)

array([4, 5, 6, 7])

In [126]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [127]:
np.setxor1d(m,n)

array([ 1,  2,  3,  8,  9, 10, 11])

In [123]:
np.isin(m,n)

array([False, False, False,  True,  True,  True,  True])

# np.clip
used to clip(limit) the values in an array

In [128]:
a

array([ 0,  3, 57, 63, 61,  0, 51, 81,  0,  0, 89,  0, 71,  0,  0],
      dtype=int32)

In [130]:
np.clip(a,a_min = 25,a_max=75)
# Values more than 75 make it 75 and values less than 25 make it 25

array([25, 25, 57, 63, 61, 25, 51, 75, 25, 25, 75, 25, 71, 25, 25],
      dtype=int32)